// === Hill Run 遊戲常數 ===

// === 步頻配置 ===
export const CADENCE_CONFIG = {
  WALK_THRESHOLD: 60,
  RUN_THRESHOLD: 120,
  MAX_CADENCE: 180,
  WALK_MAX_SPEED: 0.2,
  RUN_START_SPEED: 0.5,
  MAX_SPEED: 1,
  SPEED_LERP_FACTOR: 0.05,
  BLEND_LERP_FACTOR: 0.03,
  IDLE_TIMEOUT_TICKS: 120,
  BASE_SCROLL_SPEED: 8,
} as const

// === 賽道配置 ===
export const TRACK_CONFIG = {
  NUM_POINTS: 12,
  BASE_RADIUS: 200,
  ROAD_WIDTH: 12,
  SHOULDER_WIDTH: 3,
  ROAD_SEGMENTS: 120,
  HILL_AMPLITUDE: 18,
  HILL_FREQUENCY_1: 2,
  HILL_FREQUENCY_2: 3.7,
  HILL_RANDOM_JITTER: 6,
} as const

// === 3D 場景配置 ===
export const SCENE_CONFIG = {
  CAMERA_HEIGHT: 4,
  CAMERA_LOOK_AHEAD: 25,
  FOG_NEAR: 100,
  FOG_FAR: 300,
  RENDER_SCALE: 0.5,
  GROUND_SIZE: 800,
  GROUND_SEGMENTS: 63,
  SKY_RADIUS: 400,
  CLOUD_COUNT: 8,
  CLOUD_HEIGHT: 80,
} as const

// === 路邊物件配置 ===
export const OBJECT_CONFIG = {
  PINE_TREE_COUNT: 15,
  BROAD_TREE_COUNT: 10,
  BUSH_COUNT: 20,
  ROCK_COUNT: 12,
  FLOWER_COUNT: 15,
  NEAR_OFFSET_MIN: 8,
  NEAR_OFFSET_MAX: 15,
  MID_OFFSET_MIN: 15,
  MID_OFFSET_MAX: 25,
  FAR_OFFSET_MIN: 25,
  FAR_OFFSET_MAX: 40,
} as const

// === 遊戲設定 ===
export const GAME_CONFIG = {
  TICKS_PER_SECOND: 60,
  LOCAL_WALK_CADENCE: 80,
  LOCAL_RUN_CADENCE: 150,
  DEFAULT_STRIDE_LENGTH: 0.7,
} as const
