import type { GameInfo } from './types/game'

// === 遊戲註冊表 ===
// icon: 像素字體縮寫，iconColor: 圖示底色
export const GAMES: GameInfo[] = [
  {
    id: 'squat_jump',
    name: 'Squat Jump',
    description: 'Jump as many times as you can!',
    icon: 'SJ',
    iconColor: '#FF6B6B',
    type: 'COUNT',
    typeLabel: 'Count',
    available: true,
    module: () => import('./games/squat-jump/index'),
  },
  {
    id: 'shake_it',
    name: 'Shake It!',
    description: 'Shake your phone like crazy!',
    icon: 'SK',
    iconColor: '#4ECDC4',
    type: 'COUNT',
    typeLabel: 'Count',
    available: true,
    module: () => import('./games/shake-it/index'),
  },
  {
    id: 'virtual_run',
    name: 'Virtual Run',
    description: 'Run through beautiful scenery!',
    icon: 'VR',
    iconColor: '#95E86B',
    type: 'ENDURE',
    typeLabel: 'Endure',
    available: true,
    module: () => import('./games/virtual-run/index'),
  },
  {
    id: 'jungle_run',
    name: 'Jungle Run',
    description: 'Run through a pixel jungle!',
    icon: 'JR',
    iconColor: '#2ECC71',
    type: 'ENDURE',
    typeLabel: 'Endure',
    available: true,
    module: () => import('./games/jungle-run/index'),
  },
  {
    id: 'hill_run',
    name: 'Hill Run',
    description: 'Run through 3D hills!',
    icon: 'HR',
    iconColor: '#6BCB77',
    type: 'ENDURE',
    typeLabel: 'Endure',
    available: true,
    module: () => import('./games/hill-run/index'),
  },
  {
    id: 'pan_flip',
    name: 'Pan Flip',
    description: 'Flip the pan perfectly!',
    icon: 'PF',
    iconColor: '#FFE66D',
    type: 'COUNT',
    typeLabel: 'Count',
    available: false,
    module: null,
  },
  {
    id: 'action_command',
    name: 'Action!',
    description: 'Follow the commands!',
    icon: 'AC',
    iconColor: '#FF8A5C',
    type: 'REACT',
    typeLabel: 'React',
    available: false,
    module: null,
  },
  {
    id: 'balance',
    name: 'Balance',
    description: 'Stand on one foot!',
    icon: 'BL',
    iconColor: '#A8E6CF',
    type: 'ENDURE',
    typeLabel: 'Endure',
    available: false,
    module: null,
  },
  {
    id: 'soup_carry',
    name: 'Soup Carry',
    description: 'Keep the soup steady!',
    icon: 'SP',
    iconColor: '#DDA0DD',
    type: 'ENDURE',
    typeLabel: 'Endure',
    available: false,
    module: null,
  },
  {
    id: 'hiit',
    name: 'HIIT',
    description: 'Complete the workout!',
    icon: 'HI',
    iconColor: '#95E86B',
    type: 'HIIT',
    typeLabel: 'HIIT',
    available: false,
    module: null,
  },
  {
    id: 'high_jump',
    name: 'High Jump',
    description: 'Who jumps the highest?',
    icon: 'HJ',
    iconColor: '#87CEEB',
    type: 'PEAK',
    typeLabel: 'Peak',
    available: false,
    module: null,
  },
  {
    id: 'punch',
    name: 'Punch!',
    description: 'Hit with max power!',
    icon: 'PU',
    iconColor: '#FF4757',
    type: 'PEAK',
    typeLabel: 'Peak',
    available: false,
    module: null,
  },
]

export function getGameById(gameId: string): GameInfo | undefined {
  return GAMES.find((g) => g.id === gameId)
}
